# Generated by Django 4.1.7 on 2023-02-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='dates',
            field=models.CharField(default='default value', max_length=100),
            preserve_default=False,
        ),
    ]
